version: '3'
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    depends_on:
      - nextcloud-mariadb
    ports:
      - "60883:80"
      - "60889:443"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Makassar
    volumes:
      - /home/admintrkj/nextcloud/config:/config
      - /home/admintrkj/nextcloud/data:/data
    restart: unless-stopped
    networks:
      - nextcloud-internal

  nextcloud-mariadb:
    image: lscr.io/linuxserver/mariadb:11.6.2
    container_name: nextcloud-mariadb
    environment:
      - PUID=1000              
      - PGID=1000              
      - TZ=Asia/Makassar        
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - /home/admintrkj/nextcloud/mariadb/config:/config
    networks:
      - nextcloud-internal
    restart: unless-stopped

networks:
  nextcloud-internal:
    driver: bridge
