---
version: "2"

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW

    container_name: mariadb

    environment:
      # PUID & PGID are used to set user/group IDs.
      - PUID=1000
      - PGID=1000
      - TZ= Asia/Makassar
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REMOTE_SQL=

    volumes:
      - ../nextcloud/DATA/AppData/nextcloud-mariadb:/config

    restart: unless-stopped
