---
version: "2"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest

    container_name: nextcloud

    environment:
      # PUID & PGID are used to set user/group IDs.
      - PUID=1000
      - PGID=1000
      - TZ= Asia/Makassar

    volumes:
      - /home/admintrkj/nextcloud/DATA/AppData/nextcloud/config:/config
      - /home/admintrkj/nextcloud/DATA/AppData/nextcloud/data:/data

    ports:
      - 60889:443
      - 60883:80
      
    restart: unless-stopped
