version: "3"
services:
  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Makassar
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=${LOCAL_IP}/24,${PUBLIC_IP}
      - OVERWRITEPROTOCOL=https
      - NEXTCLOUD_TRUSTED_DOMAINS=${LOCAL_IP},${PUBLIC_IP},trkjdrive.politala.ac.id
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../nextcloud/DATA/AppData/nextcloud/config:/config
      - ../nextcloud/DATA/AppData/nextcloud/data:/data
      #- ../nextcloud/ssl/cert.pem:/config/keys/cert.pem
      #- ../nextcloud/ssl/privkey.pem:/config/keys/privkey.pem
    ports:
      - 60889:443
      - 60883:80
      
    restart: unless-stopped
